num_classes: 20
epochs: 100
log_frequency: 10
warmup_epochs: 5
lr: 0.005
min_lr: 1.0e-05
sync_bn: true
eval_freq: 1
weight_decay: 0.05
layer_decay: 1.0
pretrain_weight: 'pretrain'

criterion:
  name: CrossEntropyLoss2d
  ignore_index: 255

model:
  name: DeepV3Plus
  num_classes: $num_classes
  trunk: resnet-50
  imagenet_pretrained: false
  drop_rates:
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  c_k: 7

optimizer:
  name: AdamW
  lr: $lr
  weight_decay: $weight_decay

dataset:
  name: DatasetGenerator
  train_bs: 8
  eval_bs: 8
  n_workers: 8
  train_d_type: SVHM_LC
  train_tf_op: SVHM_LC784_finetune
  val_d_type: SVHM_LC
  val_tf_op: SVHM_LC784_finetune
  test_d_type: SVHM_LC
  test_tf_op: SVHM_LC784_finetune
  train_path: /data/gpfs/projects/punim1399/data/lc/darwin/SVHM_finalised/train
  val_path: /data/gpfs/projects/punim1399/data/lc/darwin/SVHM_finalised/train
  test_path: /data/gpfs/projects/punim1399/data/lc/darwin/SVHM_finalised/test
  img_folder_pattern: '*/images/*.png'
  mask_folder_pattern: '*/aligned_id/*.png'
  num_classes: $num_classes
  train_portion: 0.9
  type: SVHM_LC_Major
  major_classes: true
  finalised: true
