epochs: 50
log_frequency: 100
warmup_epochs: 5
blr: 0.075
lr: 0.075
blr_scale: sqrt
min_lr: 0
sync_bn: true
weight_decay: 1.0e-06
amp: true
snapshot_epoch: 50
criterion:
  name: NTXentLossLIDAug
  gather_distributed: true
  temperature: 0.1
  aug_temperature: 0.1
  aug_layers: 6
  sample_mode: weighted
  augmentations: experiments/Cholec80/tau_0.1_layers_6/rn50_784_432/policy_search/checkpoints/model_state_dict.pt
model:
  name: SimCLR
  backbone: resnet-50
  get_features: true
  c_k: 7
optimizer:
  name: LARS
  lr: $lr
  momentum: 0.9
  weight_decay: $weight_decay
dataset:
  name: DatasetGenerator
  train_bs: 48
  n_workers: 8
  train_d_type: SVHM_LC
  train_tf_op: cholec80_pretrain
  train_path: /scratch/punim1399/cholec80/videos
  img_folder_pattern: '*/*.png'
  train_portion: 1.0
  id_to_cls_name: SVHM_LC
